<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Applications Export</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #333;
        }

        .header h1 {
            font-size: 18px;
            margin-bottom: 5px;
            color: #1e293b;
        }

        .header h2 {
            font-size: 14px;
            color: #64748b;
            margin-bottom: 3px;
        }

        .header p {
            font-size: 9px;
            color: #64748b;
        }

        .stats-section {
            margin-bottom: 15px;
            padding: 10px;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 5px;
        }

        .stats-section h3 {
            font-size: 12px;
            margin-bottom: 8px;
            color: #1e293b;
        }

        .stats-grid {
            display: table;
            width: 100%;
        }

        .stat-item {
            display: table-cell;
            width: 16.66%;
            text-align: center;
            padding: 5px;
        }

        .stat-value {
            font-size: 14px;
            font-weight: bold;
            color: #1e293b;
        }

        .stat-label {
            font-size: 8px;
            color: #64748b;
            margin-top: 2px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table thead th {
            background: #64748b;
            color: white;
            padding: 8px 5px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            border: 1px solid #475569;
        }

        table tbody td {
            padding: 6px 5px;
            border: 1px solid #e5e7eb;
            font-size: 9px;
        }

        table tbody tr:nth-child(even) {
            background: #f9fafb;
        }

        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .status-pending {
            background: #fef3c7;
            color: #92400e;
        }

        .status-assigned {
            background: #dbeafe;
            color: #1e3a8a;
        }

        .status-reviewed {
            background: #d1fae5;
            color: #065f46;
        }

        .status-approved {
            background: #d1fae5;
            color: #065f46;
        }

        .status-rejected {
            background: #fee2e2;
            color: #991b1b;
        }

        .priority-badge {
            display: inline-block;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .priority-critical {
            background: #1e293b;
            color: white;
        }

        .priority-high {
            background: #fee2e2;
            color: #991b1b;
        }

        .priority-medium {
            background: #fef3c7;
            color: #92400e;
        }

        .priority-low {
            background: #d1fae5;
            color: #065f46;
        }

        .priority-normal {
            background: #e5e7eb;
            color: #374151;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #64748b;
            padding: 10px 0;
            border-top: 1px solid #e5e7eb;
        }

        .page-break {
            page-break-after: always;
        }

        .text-truncate {
            max-width: 150px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Application Reviews Report</h1>
        <h2>Reviewer Portal</h2>
        <p>Generated by: {{ $reviewer->name }} | Date: {{ now()->format('F d, Y - h:i A') }}</p>
    </div>

    <!-- Statistics Section -->
    <div class="stats-section">
        <h3>Summary Statistics</h3>
        <div class="stats-grid">
            <div class="stat-item">
                <div class="stat-value">{{ $stats['total'] }}</div>
                <div class="stat-label">Total</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ $stats['pending'] }}</div>
                <div class="stat-label">Pending</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ $stats['assigned'] }}</div>
                <div class="stat-label">Assigned</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ $stats['reviewed'] }}</div>
                <div class="stat-label">Reviewed</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ $stats['approved'] }}</div>
                <div class="stat-label">Approved</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ $stats['rejected'] }}</div>
                <div class="stat-label">Rejected</div>
            </div>
        </div>
    </div>

    <!-- Applications Table -->
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">ID</th>
                <th style="width: 18%;">Candidate</th>
                <th style="width: 15%;">Position</th>
                <th style="width: 12%;">Department</th>
                <th style="width: 10%;">Applied Date</th>
                <th style="width: 10%;">Deadline</th>
                <th style="width: 8%;">Priority</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 12%;">Reviewed</th>
            </tr>
        </thead>
        <tbody>
            @forelse($applications as $application)
                @php
                    $daysRemaining = $application->jobPosting ? (int) now()->diffInDays($application->jobPosting->deadline, false) : 0;

                    // Priority
                    if ($application->manual_priority) {
                        $priorityClass = 'priority-' . $application->manual_priority;
                        $priorityText = ucfirst($application->manual_priority);
                    } else {
                        $priorityClass = 'priority-normal';
                        $priorityText = 'Normal';
                        if ($daysRemaining <= 2) {
                            $priorityClass = 'priority-high';
                            $priorityText = 'High';
                        } elseif ($daysRemaining <= 5) {
                            $priorityClass = 'priority-medium';
                            $priorityText = 'Medium';
                        } elseif ($daysRemaining <= 10) {
                            $priorityClass = 'priority-low';
                            $priorityText = 'Low';
                        }
                    }

                    $statusClass = 'status-' . $application->status;
                @endphp
                <tr>
                    <td>{{ $application->id }}</td>
                    <td>
                        <strong>{{ $application->name_english ?? 'N/A' }}</strong><br>
                        <small style="color: #64748b;">{{ $application->email ?? 'N/A' }}</small>
                    </td>
                    <td>{{ $application->jobPosting->title ?? 'N/A' }}</td>
                    <td>{{ $application->jobPosting->department ?? 'N/A' }}</td>
                    <td>{{ $application->submitted_at ? $application->submitted_at->format('Y-m-d') : 'N/A' }}</td>
                    <td>
                        @if($application->jobPosting)
                            {{ $application->jobPosting->deadline->format('Y-m-d') }}<br>
                            <small style="color: {{ $daysRemaining <= 5 ? '#dc2626' : '#64748b' }};">
                                {{ $daysRemaining }} days
                            </small>
                        @else
                            N/A
                        @endif
                    </td>
                    <td>
                        <span class="priority-badge {{ $priorityClass }}">
                            {{ $priorityText }}
                        </span>
                    </td>
                    <td>
                        <span class="status-badge {{ $statusClass }}">
                            {{ ucfirst($application->status) }}
                        </span>
                    </td>
                    <td>
                        @if($application->reviewed_at)
                            {{ $application->reviewed_at->format('Y-m-d') }}
                        @else
                            <span style="color: #64748b;">Not Reviewed</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px; color: #64748b;">
                        No applications found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>Nepal Oil Corporation - E-Recruitment Portal | Reviewer Portal Report | Confidential Document</p>
    </div>
</body>
</html>
